config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :bikes, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create, :update]
  end

  resources :brand_models, only: [:index]

  get "/dashboard", to: 'dashboard#index'
  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :brand_model
  belongs_to :user
  has_many :bookings
  has_attachment :photo
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def available_on_date_range?(range)
    unless bookings.empty?
      return !self.booked_dates.any? { |r| r.overlaps?(range) }
    end
    true
  end

  def booked_dates
    unless bookings.empty?
      bookings.select { |b| b.status == "accepted" }.map { |b| (b.start_date..b.end_date) }
    end
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :brand_models
  belongs_to :bike
  #accepts_nested_attributes_for :brand_models
end

app/models/brand_model.rb
class BrandModel < ApplicationRecord
  belongs_to :brand
  has_many :bikes
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bikes
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show]

  # "bike"=>{"address"=>"Ahornsgade 15, København N, Denmark", "booking"=>{"start_date"=>"2017-05-24", "end_date"=>"2017-05-26"}}

  def index
    if params[:bike]

      if !params[:bike][:address].blank?
        @bikes = Bike.near(params[:bike][:address], 2)
      else
        @bikes = Bike.all # user did not fill in address field
      end

      start_date = Date.parse(params[:bike][:booking][:start_date])
      end_date = Date.parse(params[:bike][:booking][:end_date])

      if !start_date.blank? && !end_date.blank?
        date_range = (start_date..end_date)
        @bikes = @bikes.reject { |b| !b.available_on_date_range?(date_range) }
      end

    else # fallback if someone puts /bikes in the browser
      @bikes = Bike.all
    end
    # raise
  end

  def show
    @booking = Booking.new
    @mapped_bike = Gmaps4rails.build_markers(@bike) do |bike, marker|
      marker.lat bike.latitude
      marker.lng bike.longitude
    end
    # raise
  end

  def new
    @bike = Bike.new
    # @brands = Brand.all
    @brand = Brand.new
    # @brand_models = BrandModel.all
    # raise
  end

  def create
    # raise
    @bike = Bike.new(bike_params)
    @bike.daily_price_in_cents = @bike.daily_price_in_cents * 100
    if @bike.save
      redirect_to @bike
    else
      render :new
    end
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:id, :color, :electric, :daily_price_in_cents, :description, :address, :user_id, :brand_model_id, :photo)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:update]

  def create
    @bike = Bike.find(params[:bike_id])
    if current_user.nil?
      flash[:alert] = "You must be signed in to create a booking!"
      redirect_to @bike
    else
      @booking = Booking.new
      @booking.start_date = DateTime.parse(params[:booking][:start_date])
      @booking.end_date = DateTime.parse(params[:booking][:end_date])
      @booking.status = "pending"
      @booking.user = current_user
      @booking.bike = @bike
      if @booking.save
        flash[:notice] = "Booking successfully created from #{@booking.start_date} to #{@booking.end_date}!"
        redirect_to @bike
      else
        render "bikes/show"
      end
    end
  end

  def update
    @booking.status = params[:status]
    # raise
    @booking.save
    redirect_to dashboard_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end

end

app/controllers/brand_models_controller.rb
class BrandModelsController < ApplicationController

  def index
    @bike = Bike.new
    @brand = Brand.new
    @selected_brand = Brand.find(params[:brand_id])
    @brand_models = BrandModel.where(brand: params[:brand_id])

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @bookings = Booking.where(user:current_user)
    @bikes = Bike.where(user:current_user)
    @booking_requests = Booking.where(bike:current_user.bikes)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
     @bikes = Bike.last(3)
     @bike = Bike.new
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_helper.rb
module CustomHelper

  def photo_or_placeholder(photo)
    if photo
      cl_image_tag photo.path, width: 800, crop: :fit
    else
      image_tag "default_bike_photo.svg", width: 800
      # cage_tal_img "exqqhy1fq2e1kd7gqzhx", width: 800, crop: :fit
    end
  end
end

app/views/bikes/_bike_infos.html.erb
<div class="bike-box">
<%= @bike.description %> <br>
Daily price: <%= @bike.daily_price_in_cents / 100 %> DKK <br>
Electric bike: <%= @bike.electric ? "yes" : "no" %> <br>
Address: <%= @bike.address %><br>
<% if @bike.user.name %>
Owner: <%= @bike.user.name %> <br>
<% end %>
<% if @bike.user.phone_number %>
Phone: <%= @bike.user.phone_number %> <br>
</div>
<% end %>
<br>

app/views/bikes/_bike_pictures.html.erb
 <div>
 <h1><%= @bike.brand_model.brand.name %> | <%= @bike.brand_model.name %></h1>
 <%= cl_image_tag @bike.photo.path, width: 600, crop: :fit, class: "photo" if @bike.photo %>
</div>

app/views/bikes/_booking_forms.html.erb
<% unless @bike.user == current_user %>
<div class="booking-form text-center">
  <h3>Book this bike now!</h3>
  <%= simple_form_for [@bike, @booking] do |f| %>
  <div class="input-daterange input-group" id="datepicker">
    <%= f.input :start_date, as: :string, input_html: { class: 'input-sm form-control' } %>
    <%= f.input :end_date, as: :string, input_html: { class: 'input-sm form-control' } %>
  </div>
  <br>
  <%= f.submit "Book now", class: "btn btn-success click-alert"%>
  <br><br>
  <% end %>
</div>
<% end %>

app/views/bikes/_complete_form.html.erb
<%= simple_form_for bike do |f| %>
<%= f.error_notification %>
  <%= f.simple_fields_for :brands do |b|%>
      <!-- ID: #bike_brands_name -->
      <%= b.input :name, collection: Brand.all, label: "Brand", selected: selected_brand_id %>
  <% end %>
  <%# f.association :brand_model, collection: BrandModel.where() %>

<%= f.association :brand_model, collection: @brand_models, prompt: "Select model" %>
<!-- Dropdown prepare possible colors -->
<div class="form-inputs">
  <%= f.input :color %>
</div>
<!--  -->
<div class="form-inputs">
  <%= f.input :electric %>
</div>
<!-- Should divide by 100 before inputing -->
<div class="form-inputs">
  <%= f.input :daily_price_in_cents, label: 'Rental price per day (in DKK)' %>
</div>
<!--  -->
<div class="form-inputs">
  <%= f.input :description %>
</div>
<!-- #should implement Google Maps API -->
<div class="form-inputs">
  <%= f.input :address %>
</div>
<!-- #get user_id from current_user NOT going to be open for user input-->
<span>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
</span>

<!-- #2 Dropdowns to select brand and brand_model -->
<!-- maybe first hide the model & show the brand - after brand is selected, expand the model field. (javascript? Too complex?)  -->
<%# f.association :brand_model %>
<%# f.association :brand, through: :brand_model %>
<%= f.input :photo, as: :attachinary %>
<!--  -->
<div class="form-inputs">
  <%# f.input :address %>
</div>

<!-- #should implement Tuesday -->
<!-- <div class="form-inputs">
  <%# f.input :photo, as: :attachinary %>
</div> -->

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/bikes/_form.html.erb
<%= simple_form_for @bike do |f| %>
<%= f.error_notification %>

<!-- Dropdown prepare possible colors -->
<div class="form-inputs">
  <%= f.input :color %>
</div>
<!--  -->
<div class="form-inputs">
  <%= f.input :electric %>
</div>
<!-- Should divide by 100 before inputing -->
<div class="form-inputs">
  <%= f.input :daily_price_in_cents, label: 'Rental price per day (in DKK)' %>
</div>
<!--  -->
<div class="form-inputs">
  <%= f.input :description %>
</div>
<!-- #should implement Google Maps API -->
<div class="form-inputs">
  <%= f.input :address %>
</div>
<!-- #get user_id from current_user NOT going to be open for user input-->
<span>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
</span>

<!-- #2 Dropdowns to select brand and brand_model -->
<!-- maybe first hide the model & show the brand - after brand is selected, expand the model field. (javascript? Too complex?)  -->
<%= f.association :brand_model %>
<%# f.association :brand, through: :brand_model %>
<%= f.input :photo, as: :attachinary %>
<!--  -->
<div class="form-inputs">
  <%# f.input :address %>
</div>

<!-- #should implement Tuesday -->
<!-- <div class="form-inputs">
  <%# f.input :photo, as: :attachinary %>
</div> -->

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/bikes/create.html.erb
<h1>Bikes#create</h1>
<p>Find me in app/views/bikes/create.html.erb</p>

app/views/bikes/index.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <h3>
        All the bikes available from <%= params[:bike][:booking][:start_date] %> to <%= params[:bike][:booking][:end_date] %>
        <% unless params[:bike][:address].blank? %>
          <%= "around " + params[:bike][:address] %>
        <% end %>
      .</h3>
      <h4>
        <%= link_to "Modify my search", root_path %> <br><br>
        </h4>
    </div>
      <% @bikes.each do |bike| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bike.photo.path, crop: :scale; %>');">
            <div class="card-description">
              <h2><%# link_to bike.brand_model.brand.name, bike_path(bike) %> <%# bike.brand_model.name %> </h2>
              <h2><%= link_to "#{bike.brand_model.brand.name} #{bike.brand_model.name}", bike_path(bike) %> </h2>
              <h3> <%= bike.daily_price_in_cents / 100 %> DKK</h3>
              <% if bike.electric %>
                <h4>Electric</h4>
              <% end %>
          <%# bike.id %>
            </div>
        <%# link_to "See full details", @bike_path(bike), class: "card-link"  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <h1>Rent out your bike</h1>
      <div id="new_bike_form">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do  %>
  <script>
  $("#new_bike_form").change("#bike_brands_name", function(event){
    // console.log($(this).val())
    if($(event.target).attr("id") === "bike_brands_name") {
      $.ajax({
        type:"GET",
        url:"/brand_models" + "?brand_id=" + $(event.target).val()
      })
    }

  })
  </script>
<% end %>

app/views/bikes/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-md-8">
      <br>
      <%= render 'bike_pictures' %>
      <br><br>
    </div>

    <div class="col-xs-12 col-md-4">
      <br><br><br><br>
      <%= render 'booking_forms' %>
      <br> <br>
    </div>

    <br><br>
    <div class="col-xs-12 col-md-6">
      <%= render 'bike_infos' %>
    </div>
    <br><br>

    <div class="col-xs-12 col-md-8">
      <%= link_to "Back to home", bikes_path %> <br><br>
      <div id="map" style="width: 100%; height: 600px;"></div>
    </div>
    <br><br><br>

  </div>
</div>

<% content_for(:after_js) do  %>
<script>
  $(document).ready(function() {
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @mapped_bike.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  });
</script>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
    <h1> Welcome to your dashboard</h1>
    </div>
    <div class="col-xs-12">
    <h3>Hello <%= current_user.first_name %></h3>
    <h4>your info</h4>

      Your email: <%= current_user.email %> <br>
      Your phone number: <%= current_user.phone_number ? current_user.phone_number : "unspecified" %> <br>

    <em> for development purposes only, User.id:  <%= current_user.id %> </em>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-6">
    <h2>Your bookings</h2>
    <% if @bookings.empty? %>

      <p>You have not made any booking yet!</p>
      <%= link_to "Check out available bikes now!", bikes_path %>
    <% else %>


      <% @bookings.each do |booking| %>
        <ul>
          <li>
            <%= booking.start_date %> | <%= booking.end_date %> | <%= booking.bike.brand_model.brand.name %> | <%= booking.bike.brand_model.name %>
          </li>
        </ul>
      <% end %>
    <% end %>

    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-6">


    </div>
  </div>
</div>

app/views/brand_models/index.js.erb
$("#new_bike_form").html("<%= j render 'bikes/complete_form', bike: @bike, selected_brand_id: @selected_brand.id %>");
console.log("success");

app/views/dashboard/_booking_requests.html.erb
 <h3>Your booking requests</h3>

 <% @booking_requests.each do |booking_request| %>
   <div class="dashboard-card">

    <div class="dashboardcard-description">
      By <%= booking_request.user.first_name ||= booking_request.user.email %> <%= booking_request.user.phone_number ||= "" %><br>
      From <%= booking_request.start_date %> to <%= booking_request.end_date %> <br>
      For the bike: <%= link_to "#{ booking_request.bike.brand_model.name} #{booking_request.bike.brand_model.brand.name}", bike_path(booking_request.bike) %>
    </div>

    <% if booking_request.status == "pending" %>

    <div class="dashboardcard-btn">
      <%= link_to "Accept", bike_booking_path(booking_request.bike, booking_request, status: "accepted"), method: :put, class: "navbar-wagon-item navbar-wagon-button btn" %>
    </div>
    <div class="dashboardcard-btn">
      <%= link_to "Deny", bike_booking_path(booking_request.bike, booking_request, status: "denied"), method: :put, class: "navbar-wagon-item navbar-wagon-button btn" %>
    </div>

    <% else %>

    <div class="dashboardcard-status">
      <%= booking_request.status %>
    </div>

    <% end %>
  </div>
<% end %>

app/views/dashboard/_details.html.erb
<h3>Your details</h3>

      <i class="fa fa-envelope" aria-hidden="true"></i> <%= current_user.email %> <br>
      <i class="fa fa-phone" aria-hidden="true"></i> <%= current_user.phone_number ? current_user.phone_number : "phone number unspecified" %> <br>

app/views/dashboard/_your_bikes.html.erb
<% if @bikes.empty? %>


    <% elsif @bikes.length == 1 %>

    <h3>Your bike</h3>
      <ul>
        <li>
          <%= link_to "#{@bikes.first.brand_model.brand.name} | #{@bikes.first.brand_model.name}", bike_path(@bikes.first) %>
        </li>
      </ul>

    <% else %>

    <h3>Your bikes</h3>
      <% @bikes.each do |bike| %>
      <ul>
        <li>
        <%= link_to "#{bike.brand_model.brand.name} | #{bike.brand_model.name}", bike_path(bike) %>
        </li>
      </ul>
      <% end %>
    <% end %>

app/views/dashboard/_your_bookings.html.erb
<h3>Your bookings</h3>
<div class="col-xs-12">
  <% if @bookings.empty? %>

    <p>You have not made any booking yet!</p>
    <%= link_to "Check out available bikes now!", bikes_path %>

  <% else %>

    <% @bookings.each do |booking| %>
      <div class="dashboard-card">

        <div class="dashboardcard-description">
          From <%= booking.start_date %> to <%= booking.end_date %> <br>
          For the bike: <%= link_to "#{booking.bike.brand_model.brand.name} #{booking.bike.brand_model.name}", bike_path(booking.bike) %>
        </div>

        <div class="dashboardcard-status">
          <%= booking.status %>
        </div>

        <% if booking.status == "pending" || booking.status == "accepted" %>
          <% if booking.start_date < Date.today %>
          <div class="dashboardcard-btn">
            <%# link_to "Cancel", "", class: "navbar-wagon-item navbar-wagon-button btn" %>
            <%= link_to "Cancel", bike_booking_path(booking.bike, booking, status: "cancelled"), method: :put, class: "navbar-wagon-item navbar-wagon-button btn" %>

          </div>
          <% end %>
        <% end %>

      </div>
    <% end %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 text-center">
    <h1> Welcome to your dashboard <%= current_user.first_name ||= current_user.name%></h1>
    </div>

    <div class="col-xs-12 col-md-6">
     <%= render 'details' %>
    </div>

    <div class="col-xs-12 col-md-6">
      <%= render 'your_bikes' %>
    </div>

  </div>
</div>

<div class="container">
  <div class="row">

    <div class="col-xs-12 col-md-6">
      <%= render 'your_bookings' %>
    </div>

    <div class="col-xs-12 col-md-6">
      <%= render 'booking_requests' %>
    </div>

  </div>
</div>
<br><br><br><br><br><br><br><br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>

      <%= render 'shared/navbar' %>



        <%= render 'shared/flashes' %>
        <%= yield %>


        <%= render "shared/footer" %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="banner" style="background-image:linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url('<%= cl_image_path "Frederiksberg-Fonden-ladcykler_besk%C3%A5ret_bopvdz", crop: :fit %> ');">
    <div class="banner-content">
      <h1>Rent a cargo bike</h1>

      <div class="form-inline">
        <%= simple_form_for(@bike, method: :get) do |f| %>
          <%= f.input :address, as: :string, label: false, placeholder: "Address" %>
          <%= f.simple_fields_for :booking do |b| %>
          <span class="input-daterange" id="datepicker">
            <%= b.input :start_date, label: false, placeholder: "Start date", input_html: { class: "home-date-input" } %>
            <%= b.input :end_date, label: false, placeholder: "End date", input_hmtml: { class: "home-date-input" } %>
          </span>
          <% end %>
          <%= f.submit "Find your bike", class: "btn btn-success click-alert" %>
        <% end %>
      </div>

    </div>

  </div>


<div class="container">
  <div class="row">
    <div class="text-center"><h1>Last Bikes Listed</h1></div>
      <% @bikes.each do |bike| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bike.photo.path, crop: :scale; %>');">
            <div class="card-description">
              <h2><%# link_to bike.brand_model.brand.name, bike_path(bike) %> <%# bike.brand_model.name %> </h2>
              <h2><%= link_to "#{bike.brand_model.brand.name} #{bike.brand_model.name}", bike_path(bike) %> </h2>
              <h3> <%= bike.daily_price_in_cents / 100 %> DKK</h3>
              <% if bike.electric %>
                <h4>Electric</h4>
              <% end %>
          <%# bike.id %>
            </div>
        <%# link_to "See full details", @bike_path(bike), class: "card-link"  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
<script>
$(document).ready(function() {
  var bike_address = $('#bike_address').get(0);

  if (bike_address) {
    var autocomplete = new google.maps.places.Autocomplete(bike_address, { types: ['geocode'] });
    // google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
    google.maps.event.addDomListener(bike_address, 'keydown', function(e) {
      if (e.keyCode == 13) {
        e.preventDefault(); // Do not submit the form on Enter.
      }
    })
  }
});
</script>

<script>
  $(document).ready(function() {
    $('.click-alert').on('click', function(e) {

      if ($('.home-date-input').eq(0).val() === "" && $('.home-date-input').eq(0).val() === "") {
        e.preventDefault();
        sweetAlert("Please let us know \n your desired dates \n 😘");
      }

    });
  })
</script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <!--   <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div> -->
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to bikes_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <% if current_user %>
      <%= link_to t(".top_call_to_action", default: "Rent out your Bike"), new_bike_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% else %>
      <%= link_to t(".top_call_to_action", default: "Rent out your Bike"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>